name: learning
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - comm=0.1.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - ipykernel=6.25.2
  - ipython=8.16.1
  - jedi=0.19.1
  - jupyter_client=7.3.4
  - jupyter_core=5.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=3.0.11
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.2.1
  - platformdirs=3.11.0
  - prompt-toolkit=3.0.39
  - prompt_toolkit=3.0.39
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.16.1
  - python=3.10.13
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pyzmq=25.1.0
  - readline=8.2
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.11.2
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - wcwidth=0.2.8
  - wheel=0.41.2
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - certifi==2023.7.22
      - charset-normalizer==3.3.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - filelock==3.12.4
      - fonttools==4.43.1
      - fsspec==2023.9.2
      - idna==3.4
      - jinja2==3.1.2
      - kiwisolver==1.4.5
      - markupsafe==2.1.3
      - matplotlib==3.8.0
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.26.0
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.2.140
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.1.1
      - pillow==10.0.1
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - requests==2.31.0
      - sympy==1.12
      - torch==2.1.0
      - torchvision==0.16.0
      - triton==2.1.0
      - tzdata==2023.3
      - urllib3==2.0.6
